---
name: okular
version: 17.08.1
summary: Universal document viewer
description: |-
    Okular is a universal document viewer developed by KDE. Okular works on multiple platforms, including but not limited to Linux, Windows, Mac OS X, \*BSD, etc.

    Features:

    - Supported Formats: PDF, PS, Tiff, CHM, DjVu, Images, DVI, XPS, ODT, Fiction Book, Comic Book, Plucker, EPub, Fax
    - Sidebar with contents, thumbnails, reviews and bookmarks
    - Annotations support
confinement: strict
grade: stable
apps:
    okular:
        command: kf5-launch okular
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.okular
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    okular:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libchm-dev
        - libdjvulibre-dev
        - libepub-dev
        - libfreetype6-dev
        - libjpeg-dev
        - libkf5kexiv2-dev
        - libkf5khtml-dev
        - libkf5kjs-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpoppler-qt5-dev
        - libqca-qt5-2-dev
        - libqmobipocket-dev
        - libspectre-dev
        - libtiff5-dev
        - pkg-config
        - zlib1g-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/okular-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
